version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-viajes
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: menu-viajes
    depends_on:
      - db

volumes:
  db_data:
